# Generated by Django 2.0.7 on 2018-08-19 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_name', models.CharField(max_length=20)),
                ('sequence', models.TextField(max_length=800)),
                ('max_Length', models.PositiveIntegerField(choices=[(40, '40'), (50, '50'), (60, '60'), (70, '70')], default=50)),
                ('melt_Tm', models.PositiveIntegerField(default=55)),
                ('algorithm', models.CharField(choices=[('Zuker', 'Zuker'), ('Nussinov', 'Nussinov')], default='Zuker', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='SequenceOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_oligo', models.TextField(max_length=80)),
                ('oligo_melt_tm', models.PositiveIntegerField()),
                ('secondary_structure', models.TextField(max_length=80)),
                ('secondary_structure_url', models.URLField(max_length=300)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SequenceInput')),
            ],
        ),
    ]
