# Generated by Django 2.0.7 on 2018-08-19 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 8, 19, 22, 24, 11, 218081), max_length=20),
        ),
    ]
