# Generated by Django 2.0.7 on 2018-08-19 22:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180819_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceinput',
            name='algorithm',
            field=models.CharField(choices=[('Zuker', 'Zuker'), ('Nussinov', 'Nussinov')], default='Zuker', max_length=20),
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 8, 19, 22, 39, 45, 409410), max_length=60),
        ),
    ]
