# Generated by Django 2.0.7 on 2018-08-31 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180819_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequenceinput',
            name='monovalent_concentration',
            field=models.PositiveIntegerField(default=0.05),
        ),
        migrations.AddField(
            model_name='sequenceinput',
            name='oligo_concentration',
            field=models.PositiveIntegerField(default=2.5e-07),
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 8, 31, 17, 55, 42, 184509), max_length=60),
        ),
    ]
