# Generated by Django 2.0.7 on 2018-09-01 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180831_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequenceoutput',
            old_name='secondary_structure_url',
            new_name='all_results_url',
        ),
        migrations.RemoveField(
            model_name='sequenceoutput',
            name='oligo_melt_tm',
        ),
        migrations.RemoveField(
            model_name='sequenceoutput',
            name='output_oligo',
        ),
        migrations.AddField(
            model_name='sequenceoutput',
            name='assembly_scheme',
            field=models.TextField(default='Not provided', max_length=8000),
        ),
        migrations.AddField(
            model_name='sequenceoutput',
            name='output_oligos',
            field=models.TextField(default='Not provided', max_length=8000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequenceoutput',
            name='primer_dimers',
            field=models.TextField(default='Not Provided', max_length=8000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 9, 1, 0, 4, 15, 192441), max_length=60),
        ),
        migrations.AlterField(
            model_name='sequenceoutput',
            name='secondary_structure',
            field=models.TextField(max_length=8000),
        ),
    ]
