# Generated by Django 2.0.7 on 2018-09-03 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180901_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 9, 3, 18, 22, 49, 986831), max_length=60),
        ),
    ]
