# Generated by Django 2.0.7 on 2018-09-04 01:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180903_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 9, 4, 1, 33, 35, 474400), max_length=60),
        ),
        migrations.AlterField(
            model_name='sequenceoutput',
            name='sequence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.SequenceInput'),
        ),
    ]
