# Generated by Django 2.0.7 on 2018-10-02 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180904_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceinput',
            name='melt_Tm',
            field=models.FloatField(default=55),
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='monovalent_concentration',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='oligo_concentration',
            field=models.FloatField(default=2.5e-07),
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 10, 2, 17, 34, 55, 222214), max_length=60),
        ),
    ]
