# Generated by Django 2.0.7 on 2018-12-05 23:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181002_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequenceoutput',
            name='secondary_structure',
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 12, 5, 23, 7, 33, 92138), max_length=60),
        ),
    ]
