# Generated by Django 2.1.4 on 2018-12-06 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181205_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequenceinput',
            name='max_Length',
            field=models.PositiveIntegerField(choices=[(50, '50'), (60, '60'), (70, '70')], default=50),
        ),
        migrations.AlterField(
            model_name='sequenceinput',
            name='sequence_name',
            field=models.CharField(default=datetime.datetime(2018, 12, 6, 5, 57, 33, 156610), max_length=60),
        ),
    ]
